const catalog={
'linux-101':{title:'Linux 101',topic:'Linux',difficulty:'קל',xp:120,time:'25 דק׳',desc:'למד ניווט, קבצים ופקודות בסיסיות בטרמינל.',tasks:[
{title:'ברוכים הבאים ל־Linux',type:'lesson',html:'<h2>מה זה Linux?</h2><p>Linux היא משפחה של מערכות הפעלה. בעולם הסייבר פוגשים אותה בשרתים, ענן, כלי פיתוח ומעבדות. בחדר הזה נתרגל רק בתוך סימולטור בטוח בדפדפן.</p><div class="learn-box"><b>מושגים חשובים</b><p><code>pwd</code> מציג מיקום, <code>ls</code> מציג קבצים, <code>cd</code> עובר תיקייה ו־<code>cat</code> קורא קובץ.</p></div>',question:'איזו פקודה מציגה את התיקייה הנוכחית?',answer:'pwd',hint:'שלוש אותיות: print working directory'},
{title:'ניווט בטרמינל',type:'terminal',html:'<h2>משימת Terminal</h2><p>מצא את הדגל שנמצא בסביבת התרגול. השתמש ב־<code>ls</code>, <code>ls -a</code> ו־<code>cat</code>.</p>',goal:'THMIL{linux_first_flag}'},
{title:'בדיקת ידע',type:'quiz',html:'<h2>סיכום</h2><p>לפני שמסיימים, בדיקה קצרה.</p>',question:'איזו פקודה משמשת להצגת תוכן של קובץ?',options:['cat','mkdir','pwd','whoami'],answer:'cat'}]},
'network-basics':{title:'יסודות הרשת',topic:'רשתות',difficulty:'קל',xp:140,time:'30 דק׳',desc:'הכר כתובות IP, פורטים ופרוטוקולים נפוצים.',tasks:[
{title:'IP ופורטים',type:'lesson',html:'<h2>איך מחשבים מדברים?</h2><p>כתובת IP מזהה ממשק ברשת. פורט עוזר למערכת להפנות תעבורה לשירות המתאים. TCP ו־UDP הם פרוטוקולי תעבורה נפוצים.</p>',question:'מה מזהה שירות או יישום מסוים על מחשב?',answer:'פורט',hint:'מספר כמו 80 או 443'},
{title:'התאמת פרוטוקולים',type:'quiz',html:'<h2>HTTP</h2><p>בחר את הפורט המזוהה בדרך כלל עם HTTPS.</p>',question:'מהו הפורט הנפוץ של HTTPS?',options:['21','53','80','443'],answer:'443'},
{title:'DNS',type:'lesson',html:'<h2>DNS</h2><p>DNS מתרגם שמות מתחם לכתובות ומאפשר ליישומים למצוא שירותים בלי לזכור כתובות מספריות.</p>',question:'מה ראשי התיבות DNS?',answer:'domain name system',hint:'אפשר לענות באנגלית'}]},
'web-basics':{title:'איך ה־Web עובד',topic:'Web',difficulty:'קל',xp:130,time:'25 דק׳',desc:'HTTP, בקשות, תגובות, Cookies ודפדפן.',tasks:[
{title:'Request & Response',type:'lesson',html:'<h2>HTTP בפשטות</h2><p>הדפדפן שולח Request לשרת והשרת מחזיר Response. התגובה כוללת status, headers ולעיתים body.</p>',question:'איך נקראת ההודעה שהדפדפן שולח לשרת?',answer:'request',hint:'המילה האנגלית לבקשה'},
{title:'קודי סטטוס',type:'quiz',html:'<h2>Status codes</h2><p>קודי HTTP מתארים את תוצאת הבקשה.</p>',question:'איזה קוד בדרך כלל אומר Not Found?',options:['200','301','404','500'],answer:'404'},
{title:'Cookies',type:'lesson',html:'<h2>Cookies</h2><p>Cookie הוא ערך קטן שהדפדפן שומר ושולח לפי כללי האתר. הוא יכול לשמש session והעדפות.</p>',question:'האם Cookie נשמר בצד הדפדפן? כן/לא',answer:'כן',hint:'חשוב על המקום שבו האתר זוכר session'}]},
'logs-first':{title:'היכרות עם לוגים',topic:'Blue Team',difficulty:'קל',xp:150,time:'30 דק׳',desc:'למד לקרוא אירועים ולזהות סימנים חריגים.',tasks:[{title:'מהו Log?',type:'lesson',html:'<h2>אירועים מספרים סיפור</h2><p>לוג מתעד אירועים: זמן, מקור, פעולה ותוצאה. אנשי Blue Team משתמשים בלוגים כדי להבין מה קרה.</p>',question:'איזה שדה עוזר לסדר אירועים כרונולוגית?',answer:'זמן',hint:'timestamp'},{title:'מצא חריגה',type:'quiz',html:'<h2>ניתוח בסיסי</h2><p>נרשמו 2 כניסות מוצלחות ו־35 ניסיונות כושלים בדקה מאותו מקור.</p>',question:'איזה אירוע נראה חריג?',options:['2 כניסות מוצלחות','35 ניסיונות כושלים','פתיחת הדפדפן'],answer:'35 ניסיונות כושלים'}]},
'linux-permissions':{title:'הרשאות Linux',topic:'Linux',difficulty:'בינוני',xp:200,time:'40 דק׳',desc:'Users, Groups, chmod ו־ownership דרך תרגול.',tasks:[{title:'rwx',type:'lesson',html:'<h2>Read, Write, Execute</h2><p>הרשאות Linux מיוצגות לעיתים כ־r, w, x עבור קריאה, כתיבה והרצה.</p>',question:'איזו אות מייצגת execute?',answer:'x',hint:'r,w,?'},{title:'בדיקה',type:'quiz',html:'<h2>הרשאות</h2>',question:'איזו פקודה משנה הרשאות קובץ?',options:['chmod','cat','pwd','echo'],answer:'chmod'}]},
'dns-detective':{title:'בלש DNS',topic:'רשתות',difficulty:'בינוני',xp:220,time:'45 דק׳',desc:'פתור תעלומה באמצעות רשומות DNS וניתוח מידע.',tasks:[{title:'רשומות',type:'lesson',html:'<h2>DNS Records</h2><p>רשומת A מקשרת שם לכתובת IPv4. רשומת MX מתארת שרתי דואר.</p>',question:'איזו רשומה קשורה לדואר?',answer:'mx',hint:'שתי אותיות'},{title:'חקירה',type:'quiz',html:'<h2>בחר רשומה</h2>',question:'איזו רשומה מחזירה IPv4?',options:['A','MX','TXT','CNAME'],answer:'A'}]},
'http-lab':{title:'מעבדת HTTP',topic:'Web',difficulty:'בינוני',xp:240,time:'50 דק׳',desc:'חקור בקשות ותגובות בתוך אפליקציית תרגול.',tasks:[{title:'Methods',type:'lesson',html:'<h2>HTTP Methods</h2><p>GET משמש בדרך כלל לקריאה ו־POST לשליחת נתונים/פעולה בהתאם ל־API.</p>',question:'איזו method מזוהה בדרך כלל עם קריאה?',answer:'get',hint:'3 אותיות'},{title:'Headers',type:'quiz',html:'<h2>Content-Type</h2>',question:'מה מתאר Content-Type?',options:['סוג תוכן','כתובת IP','סיסמה','פורט'],answer:'סוג תוכן'}]},
'soc-alert':{title:'התראת SOC',topic:'Blue Team',difficulty:'בינוני',xp:260,time:'50 דק׳',desc:'מיין אירועים וקבע אילו התראות דורשות בדיקה.',tasks:[{title:'Triage',type:'lesson',html:'<h2>מיון התראות</h2><p>ב־SOC בודקים הקשר, חומרה, נכס מושפע וראיות לפני החלטה.</p>',question:'מה חשוב לבדוק לפני קביעה שהתראה אמיתית?',answer:'הקשר',hint:'context'},{title:'עדיפות',type:'quiz',html:'<h2>מה קודם?</h2>',question:'איזו התראה דורשת עדיפות גבוהה יותר?',options:['כשל כניסה יחיד','הרבה כשלים ואז כניסה מוצלחת לחשבון מנהל','עדכון תוכנה צפוי'],answer:'הרבה כשלים ואז כניסה מוצלחת לחשבון מנהל'}]},
'ctf-kotel':{title:'CTF: הכותל הדיגיטלי',topic:'CTF',difficulty:'מתקדם',xp:400,time:'75 דק׳',desc:'אתגר חקירה רב־שלבי עם רמזים ודגל סופי.',tasks:[{title:'מבוא',type:'lesson',html:'<h2>CTF בטוח</h2><p>האתגר מתרחש כולו בסימולציה מקומית. חפש רמזים בתוך הקבצים המדומים בלבד.</p>',question:'איפה מתבצע האתגר?',answer:'בסימולציה',hint:'לא מול מערכת אמיתית'},{title:'מצא דגל',type:'terminal',html:'<h2>חקירה</h2><p>השתמש בפקודות הסימולטור כדי למצוא את הדגל.</p>',goal:'THMIL{jerusalem_ctf_complete}'}]}}
;
const params=new URLSearchParams(location.search), id=params.get('id')||'linux-101', room=catalog[id]||catalog['linux-101'];
let state=JSON.parse(localStorage.getItem('thmil-progress')||'{"xp":0,"completed":[]}');state.tasks=state.tasks||{};state.tasks[id]=state.tasks[id]||[];let current=0;
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem('thmil-progress',JSON.stringify(state))}function done(i){return state.tasks[id].includes(i)}
function complete(i){if(done(i))return;state.tasks[id].push(i);if(state.tasks[id].length===room.tasks.length&&!state.completed.includes(id)){state.completed.push(id);state.xp+=room.xp;toast(`החדר הושלם! קיבלת ${room.xp} XP 🎉`)}save();renderNav();renderProgress();renderTask()}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function renderProgress(){const n=state.tasks[id].length,total=room.tasks.length,p=Math.round(n/total*100);$('#progressText').textContent=p+'%';$('#progressBar').style.width=p+'%';$('#taskCount').textContent=`${n} מתוך ${total} משימות הושלמו`;$('#roomXp').textContent=state.xp+' XP'}
function renderNav(){$('#taskNav').innerHTML=room.tasks.map((t,i)=>`<button class="task-nav-item ${i===current?'active':''} ${done(i)?'done':''}" data-i="${i}"><span>${done(i)?'✓':i+1}</span><div><b>${esc(t.title)}</b><small>${done(i)?'הושלם':'משימה '+(i+1)}</small></div></button>`).join('');document.querySelectorAll('.task-nav-item').forEach(b=>b.onclick=()=>{current=+b.dataset.i;renderNav();renderTask()})}
function answerBox(t,i){if(t.type==='quiz')return `<div class="challenge"><h3>${esc(t.question)}</h3><div class="option-grid">${t.options.map(o=>`<button class="answer-option" data-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div><p class="answer-status" id="answerStatus"></p></div>`;return `<div class="challenge"><h3>${esc(t.question)}</h3><div class="answer-row"><input id="answerInput" placeholder="הקלד תשובה..." autocomplete="off"><button class="btn primary" id="checkAnswer">בדיקה</button></div><button class="hint-btn" id="hintBtn">💡 הצג רמז</button><p class="hint-text" id="hintText"></p><p class="answer-status" id="answerStatus"></p></div>`}
function terminal(t){return `<div class="room-terminal"><div class="terminal-head"><span></span><span></span><span></span><b>student@thmil-lab</b></div><div class="room-term-output" id="termOut">TryHackMe IL Safe Lab\nהקלד help לעזרה.\n\n</div><label><span>student@lab:~$</span><input id="termInput" autocomplete="off" spellcheck="false"></label></div><div class="flag-row"><input id="flagInput" placeholder="THMIL{...}" dir="ltr"><button class="btn primary" id="flagBtn">שלח דגל</button></div><p class="answer-status" id="answerStatus"></p>`}
function renderTask(){const t=room.tasks[current];$('#taskContent').innerHTML=`<div class="task-kicker">TASK ${current+1} / ${room.tasks.length}</div>${t.html}${done(current)?'<div class="completed-banner">✓ המשימה הושלמה</div>':''}${t.type==='terminal'?terminal(t):answerBox(t,current)}`;$('#prevTask').disabled=current===0;$('#nextTask').disabled=current===room.tasks.length-1;$('#prevTask').onclick=()=>{if(current>0){current--;renderNav();renderTask()}};$('#nextTask').onclick=()=>{if(current<room.tasks.length-1){current++;renderNav();renderTask()}};
if(t.type==='quiz')document.querySelectorAll('.answer-option').forEach(b=>b.onclick=()=>check(b.dataset.answer,t));else if(t.type==='lesson'){const b=$('#checkAnswer');b.onclick=()=>check($('#answerInput').value,t);$('#answerInput').onkeydown=e=>{if(e.key==='Enter')b.click()};$('#hintBtn').onclick=()=>$('#hintText').textContent=t.hint||'קרא שוב את ההסבר למעלה.'}else setupTerminal(t)}
function norm(s){return String(s).trim().toLowerCase()}function check(v,t){const st=$('#answerStatus');if(norm(v)===norm(t.answer)){st.textContent='✓ תשובה נכונה';st.className='answer-status success';complete(current)}else{st.textContent='לא בדיוק — נסה שוב.';st.className='answer-status error'}}
function setupTerminal(t){const files=id==='ctf-kotel'?{'brief.txt':'בדוק קבצים מוסתרים עם ls -a','.clue':'הדגל נמצא ב־flag.txt','flag.txt':'THMIL{jerusalem_ctf_complete}'}:{'readme.txt':'נסה ls -a כדי לראות הכול','.hint':'קרא את flag.txt','flag.txt':'THMIL{linux_first_flag}'};const out=$('#termOut'),input=$('#termInput');input.onkeydown=e=>{if(e.key!=='Enter')return;const cmd=input.value.trim();input.value='';let r='';if(cmd==='help')r='פקודות: pwd, whoami, ls, ls -a, cat <file>, clear';else if(cmd==='pwd')r='/home/student';else if(cmd==='whoami')r='student';else if(cmd==='ls')r='readme.txt';else if(cmd==='ls -a')r='.  ..  '+Object.keys(files).join('  ');else if(cmd==='clear'){out.textContent='';return}else if(cmd.startsWith('cat ')){const f=cmd.slice(4).trim();r=files[f]||`cat: ${f}: No such file`}else r=cmd?`${cmd}: command not found`:' ';out.textContent+=`student@lab:~$ ${cmd}\n${r}\n`;out.scrollTop=out.scrollHeight};$('#flagBtn').onclick=()=>{const st=$('#answerStatus');if(norm($('#flagInput').value)===norm(t.goal)){st.textContent='✓ דגל נכון!';st.className='answer-status success';complete(current)}else{st.textContent='הדגל לא נכון. המשך לחקור.';st.className='answer-status error'}}}
document.title=room.title+' | TryHackMe IL';$('#roomTitle').textContent=room.title;$('#roomTopic').textContent=room.topic.toUpperCase()+' ROOM';$('#roomDesc').textContent=room.desc;$('#roomMeta').innerHTML=`<span class="tag easy">${room.difficulty}</span><span class="tag">${room.time}</span><span class="tag">${room.xp} XP</span>`;renderNav();renderProgress();renderTask();